DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS item;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE item (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  'name' VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  purchased BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES user (id)
);